### ISSUE TITLE
Support git repositories beyond github including bitbucket and gitlab

### ISSUE THREAD

**Issue by gjwgit** [mlhubber/mlhub#100]
Currently only github repositories are supported as source of MLHub packages. Any git repository should be supported, including bitbucket and gitlab and independently run git repositories.

**Comment by simonzhaoms** [comment]
A curated list of source code hosting facilities can be found at [Comparison of source-code-hosting facilities -- Wikipedia](https://en.wikipedia.org/wiki/Comparison_of_source-code-hosting_facilities)

**Comment by simonzhaoms** [comment]
I collected a list of URL patterns and APIs for GitHub, GitLab and Bitbucket that are useful: https://github.com/simonzhaoms/tips/blob/master/github/compose-github-links.md

**Comment by simonzhaoms** [comment]
- [X] Support for GitLab
- [x] Support for Bitbucket
- [x] Generalization for other git repos
- [ ] Support for pull/merge request
  - [ ] GitLab
  - [ ] Bitbucket

**Comment by gjwgit** [comment]
For now closing this - mostly implemeneted and working for gitlab and bitbucket.

What was the pull/merge issue? Create new issue if required.
