### ISSUE TITLE
azspeech: New commands

### ISSUE THREAD

**Issue by gjwgit** [mlhubber/mlhub#151]
Add TRANSLATE, INTENT, CONVERSATION, RECOGNISE

**Comment by JingjingShii** [comment]
CONVERSATION and RECOGNISE in Azure don't support Python

**Comment by gjwgit** [comment]
If Python SDK is not available then can they be done through the RESTful interface.

**Comment by JingjingShii** [comment]
- [ ] audio files in RECOGNISE support url as well. (Now it only supports path)
- [x] modify demo, make it more attractive
- [x] add translate, intent and recognise in demo
- [x] Update readme

**Comment by JingjingShii** [comment]
RECOGNISE supports wav file as the input only. This service is to verify if a speaker matches an enrolled voice. I think it's better to use the real wav file instead of the URL.
