### ISSUE TITLE
No command line in Iris package

### ISSUE THREAD

**Issue by JingjingShii** [mlhubber/mlhub#164]
I followed the instruction in 3.2 Hello World (https://mlhub.ai/survivor/hello-world.html) to run the Iris package. When I tried 
`ml gui iris`
It showed `mlhub: The command 'gui' was not found for this model 'iris'.`
After did `ml  commands iris`, I found a similar command-line `ml display iris`

Also, `ml score iris` and `ml train iris` were not found as well.

**Comment by gjwgit** [comment]
These commands are not (yet) implemented for iris. Remove from the book for now.
