### ISSUE TITLE
Value error in azcv

### ISSUE THREAD

**Issue by JingjingShii** [mlhubber/mlhub#166]
When running `ml type azcv https://bit.ly/3bNGSBv`, got the error:
![image](https://user-images.githubusercontent.com/26078356/111947290-43146300-8b31-11eb-9759-cd3995f9dbab.png)

**Comment by gjwgit** [comment]
This issue belongs to the gjwgit/azcv repository.

**Comment by JingjingShii** [comment]
It seems all `ml type xxx` have the same issue.

**Comment by JingjingShii** [comment]
It seems all `ml type azcv xxx` have the same issue.
