### ISSUE TITLE
The URL does not appear to exist

### ISSUE THREAD

**Issue by JingjingShii** [mlhubber/mlhub#167]
When I try to run `ml ocr azcv http://www.handwrittenocr.com/images/Handwriting/16.jpg`, the error occurs:
`The URL does not appear to exist. Please check.
    http://www.handwrittenocr.com/images/Handwriting/16.jpg`
When clicking the URL, the web page is 404 Not Found.

**Comment by gjwgit** [comment]
The URL has been updated to be 

`$ ml ocr azcv https://bit.ly/319WJUM`
