### ISSUE TITLE
File Not Found in speech2txt package

### ISSUE THREAD

**Issue by JingjingShii** [mlhubber/mlhub#169]
When running `ml demo speech2txt`, got the error:
![image](https://user-images.githubusercontent.com/26078356/112086013-9ba23980-8bdf-11eb-9c31-3ec0959d93a6.png)

**Comment by gjwgit** [comment]
The URL in MLHUB.yaml for this package downloads `https://raw.githubusercontent.com/Azure-Samples/cognitive-services-speech-sdk/master/samples/csharp/sharedcontent/console/whatstheweatherlike.wav` into `samples/csharp/sharedcontent/console`. 

This is not where the demo.py expects it to be.

Update MLHUB.yaml to place it at the root of .mlhub/speech2txt.

Updated in Version 0.1.3
