### ISSUE TITLE
Error in sgnc package 

### ISSUE THREAD

**Issue by JingjingShii** [mlhubber/mlhub#170]
When trying to run `ml configure sgnc`, got the error:
![image](https://user-images.githubusercontent.com/26078356/112086627-ac9f7a80-8be0-11eb-8bc6-2dcfab7cb72f.png)

**Comment by gjwgit** [comment]
Fixed in MLHUB.yaml file of sgnc package: scipy=1.4.1 should have been scipy==1.4.1 (double equal) as per message on last line of screen shot.

Updated package to version 0.1.1
