### ISSUE TITLE
Determine default branch in place of master.

### ISSUE THREAD

**Issue by gjwgit** [mlhubber/mlhub#177]
The git repositories are migrating from master as the default to main as the default. 

When the ports package was migrated the install failed:

```
$ ml install ports


mlhub: Missing url: https://codeload.github.com/gjwgit/ports/zip/master
       please notify package author.
The file type cannot be determined.
Please give it a file name with explicit valid archive extension: ^C
```

Similarly:

```
$ ml install gjwgit/ports@master
```

But this worked just fine:

```
$ ml install gjwgit/ports@main
```

This might need fixing in mlhub/utils.py where self.ref defaults to master.

**Comment by gjwgit** [comment]
A repository has a default branch - we need to query the repo, identify the default branch, and use that:
 
```
$ curl -s -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/gjwgit/ports | jq .default_branch
"main"

$ curl -s -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/gjwgit/rain | jq .default_branch
"master"
```

**Comment by gjwgit** [comment]
"The default branch works for github now. Still looking for way to determine default branch for gitlab and bitbucket."

**Comment by gjwgit** [comment]
For gitlab: 

```
$  curl -s https://gitlab.com/api/v4/projects/kayontoga%2Fcars | jq .default_branch
"master"
``

**Comment by gjwgit** [comment]
For bitbucket:

```
curl -s https://api.bitbucket.org/2.0/repositories/kayontoga/rattle | jq .mainbranch.name
"master"
```

**Comment by JingjingShii** [comment]
Thanks, Graham. Fo gitlab api, I thought it had /repository after project name

**Comment by JingjingShii** [comment]
When using requests to access the api,  the rate limit allows for up to 60 requests per hour for the unauthenticated requests. 
As for the users who use mlhub, I don't think they'll install more than 60 packages per hour.
