### ISSUE TITLE
Unit testing: mlhub (the whole pacakge)

### ISSUE THREAD

**Issue by JingjingShii** [mlhubber/mlhub#193]

**Comment by gjwgit** [comment]
Decide on using the [exactly](https://github.com/emilkarlen/exactll) framework for testing command lines.

```
pip3 install exactly
```

Added test directory to contain the unit test cases.

Added new Makefile targets:

```
$ make test        # Run all the tests.
$ make test 200 # Run just the test(s) starting with 200_
```

**Comment by gjwgit** [comment]
Repurpose this issue as a task to add individual unit testing to specific packages using `exactly`

- [x] amimate
- [x] azspeech
