### ISSUE TITLE
Support two or more keys in private row

### ISSUE THREAD

**Issue by JingjingShii** [mlhubber/mlhub#215]
```
private:
  Azure Speech: key*, location
  Google Speech: key*
```

**Comment by gjwgit** [comment]
For a single key it is then:
```
private: Azure Speech: key*, location
```

**Comment by JingjingShii** [comment]
In yaml file:
for multiple keys:
>   private      :
>     Azure subscription : key*, location
>     Google speech      : key*, Google location

for single key:

>   private      :
>     Azure subscription : key*, location





In json file:
for multiple keys:

> Azure speech:
>       {
>            key: xxx,
>           location: xxxx,
>       },
> Google speech:
>      {
>          key: xxx,
>      }

for single key:

> Azure speech:
>       {
>            key: xxx,
>           location: xxxx,
>       }
>
