### ISSUE TITLE
az: migrate all to using private.json

### ISSUE THREAD

**Issue by gjwgit** [mlhubber/mlhub#224]
The new method for handling the Azure Services key is through the CONFIGURE command, using the private: entry in MLHUB.yaml.

Migrate each of the az models to using this approach:

- [x] azcv
- [x] azface
- [x] azlang
- [x] azluis
- [x] azspeech
- [x] aztext
- [x] aztranslate

**Comment by gjwgit** [comment]
Merge azluis into azlang.

**Comment by JingjingShii** [comment]
> Merge azluis into azlang.

I remove canned.pkl because I don't think we allow users to run without private information.

**Comment by JingjingShii** [comment]
I remove canned.pkl because I don't think we allow users to run demo in azlang without private information.
