### ISSUE TITLE
Next step suggestion is unaware of the parameters of the command

### ISSUE THREAD

**Issue by simonzhaoms** [mlhubber/mlhub#26]
The next step suggestion for commands such as `score` should be aware of its parameters.  For example, the suggestion after `ml display iris` should look like `ml score iris <csv file>`.  However, it cannot be known by `ml` command in advance.  And I think these help messages should be provided by the model developer.

```console
$ ml display iris
null device 
          1 

To apply model to your data (CSV with header and 4 numeric columns):

  $ ml score iris


$ ml score iris
An error was encountered:

Error in file(file, "rt") : cannot open the connection
Calls: %>% -> eval -> eval -> read.csv -> read.table -> file
In addition: Warning message:
In file(file, "rt") : cannot open file 'NA': No such file or directory
Execution halted
```

**Comment by gjwgit** [comment]
Coupled with #27
