### ISSUE TITLE
CONFIGURE should recognise requirements.txt, configure.sh, configure.py, configure.R

### ISSUE THREAD

**Issue by gjwgit** [mlhubber/mlhub#6]
Using a logical (if any) predetermined priority, the CONFIGURE command should search for and execute the alternative configuations. Currently we see configure.sh simply doing Rscript configure.R, for example. The model package builder should not have to worry about that.

What is a sensible order, and do we do them all or just the first?

**Comment by gjwgit** [comment]
Also the dependencies listed in DESCRIPTION.yaml, if any, should always be displayed, irresepective of whether there is a configure script.

**Comment by gjwgit** [comment]
The dependencies listed in DESCRIPTION.yaml should be installed as part of the CONFIGURE command. Note that all installation should be in the model package folder.

**Comment by gjwgit** [comment]
DESCRIPTION.yaml should be dealt with first. Then any of requirements.txt, configure.sh, configure.py, configure.R - maybe.

**Comment by simonzhaoms** [comment]
I think executing `ml configure` after `ml install` automatically by default would be better, thus users don't need to `ml configure` manually, then `ml demo` won't fail if the users forget to execute `ml configure`.

**Comment by gjwgit** [comment]
Close this issue as most of it addressed. Open new issue around running configure as part of the install.
