### ISSUE TITLE
Check and advise on mlhub pre-requisities

### ISSUE THREAD

**Issue by gjwgit** [mlhubber/mlhub#7]
E.g., if R is not installed (and so Rscript would fail) then advise on how to install R.

**Comment by gjwgit** [comment]
So, `ml configure` will install for R: r-base, r-cran-devtools, libxml2-dev. Python is actually usually already installed, though may need to install pip. May also need libcurl4-openssl-dev, libssl-dev, libgit2-dev( See animate)?

**Comment by simonzhaoms** [comment]
As well as `pandoc`.  See #81

**Comment by simonzhaoms** [comment]
Added in commit fcad82d
