### ISSUE TITLE
README fails silently if pandoc is not installed

### ISSUE THREAD

**Issue by gjwgit** [mlhubber/mlhub#81]
Need to test that pandoc is installed for conversion of md to txt, or else code using a python package (if such exists) to do the same.

**Comment by simonzhaoms** [comment]
Related to #7

**Comment by simonzhaoms** [comment]
Sovled in commit fcad82d

When one of the commands in a pipe fails, such as `pandoc -t plain README.rst` in 

```
pandoc -t plain README.rst | awk '/^Usage$$/{exit}{print}' | perl -00pe0 > README.txt
```

the return code may still be 0, if afterwards commands succeed.  This behaviour can be changed by `set -o pipefail`.
