### ISSUE TITLE
CONFIGURE: allow a --yes option to answer yes by default to each install request

### ISSUE THREAD

**Issue by gjwgit** [mlhubber/mlhub#91]
`$ ml configure --yes objects`

This will configure the objects package without asking the user to confirm each dependency install.

Note that do not assume yes for the cached objects if they have already been downloaded. Perhaps even change the cache question from

`The file is cached.  Would you like to download it again [y/N]?`

to

`The file is cached.  Reuse the cached version [Y/n]?`

**Comment by simonzhaoms** [comment]
Added in 5873f4b

**Comment by gjwgit** [comment]
Is `--yes` as an alias for `-y` possible? Also allow --yes for cached files?

**Comment by simonzhaoms** [comment]
It is `-y` not `--yes`, and not for cached files yet.
`argparse` does not accept alias for subcommand, though it accept alias for upper level command.

I am working on cached file.

**Comment by simonzhaoms** [comment]
Solved in 12fd05f

**Comment by gjwgit** [comment]
Thanks. 

For` -y` and `--yes`, having no alias, you should be able to add `'--yes'` to the arguments of configure in constants.py and then in `configure_model()` replace `args.y` with `(args.y | args.yes)` - via a single constant perhaps like `YES=(args.y | args.yes)`?

**Comment by simonzhaoms** [comment]
Yes, it is very helpful.
Thanks 😄

**Comment by simonzhaoms** [comment]
Done in 69f7508
