### ISSUE TITLE
CONFIGURE: package configure is now refularly asking to upgrade pip

### ISSUE THREAD

**Issue by gjwgit** [mlhubber/mlhub#92]
```
$ ml configure colorize 

*** The following required system packages are already installed:
  python3-numpy python3-pydot python3-matplotlib

Do you want to upgrade pip [Y/n]? 
```

This is being asked for many configure's now. From a user perspective it is puzzling. Does it need to be upgraded/asked?

**Comment by simonzhaoms** [comment]
Fixed in dd4aeeb

It is a bug.  The code always run pip upgrade instead of checking whether pip is the latest version.
