### ISSUE TITLE
CONFIGURE: Need to check if pip packages are already installed

### ISSUE THREAD

**Issue by simonzhaoms** [mlhubber/mlhub#94]

**Comment by simonzhaoms** [comment]
Fix in 1ae5621

**Comment by gjwgit** [comment]
After running `ml configure objects` should the next run also reinstall Pillow and numpy?

```
26 Mar 12:40:36 gjw@yoga ~$ ml configure --yes objects

*** The following required system packages are already installed:
  python3-packaging python3-matplotlib python3-ipython python3-toolz python3-keras

*** The following required ${src} packages are already installed:
  tensorflow

*** Installing Python package pillow by pip3 ...
[...]
*** Installing Python package numpy==1.13.3 by pip3 ...
[...]
26 Mar 12:40:59 gjw@yoga ~$ ml configure --yes objects

*** The following required system packages are already installed:
  python3-packaging python3-matplotlib python3-ipython python3-toolz python3-keras

*** The following required ${src} packages are already installed:
  tensorflow

*** Installing Python package pillow by pip3 ...
[...]
*** Installing Python package numpy==1.13.3 by pip3 ...
[...]
```

**Comment by simonzhaoms** [comment]
Fixed in a432224

**Comment by simonzhaoms** [comment]
**Note**:
* Older version of pip (such as 9.0.2) will keep multiple versions of a package in its path.  If you `pip install xxx==2.0`, and then `pip install xxx==1.0`, `pip show xxx` will show you the bigger version you have ever installed, which in this case is `2.0`.  However, if you `python -c 'import xxx; print(xxx.__version__)'`, you will find the version you actually use is `1.0`.
* In addition, not all packages have an attribute `__version__`, so `python -c 'import xxx; print(xxx.__version__)'` won't always give the version number of the package `xxx`.

**Comment by gjwgit** [comment]
Reference also #96
